# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyPezdemo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(125, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_addpole = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addpole.setGeometry(QtCore.QRect(420, 470, 75, 23))
        self.pushButton_addpole.setObjectName("pushButton_addpole")
        self.pushButton_deletepole = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deletepole.setGeometry(QtCore.QRect(530, 470, 75, 23))
        self.pushButton_deletepole.setObjectName("pushButton_deletepole")
        self.pushButton_deletezero = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deletezero.setGeometry(QtCore.QRect(930, 470, 75, 23))
        self.pushButton_deletezero.setObjectName("pushButton_deletezero")
        self.pushButton_addzero = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addzero.setGeometry(QtCore.QRect(820, 470, 75, 23))
        self.pushButton_addzero.setObjectName("pushButton_addzero")
        self.polezeroGraph = PlotWidget(self.centralwidget)
        self.polezeroGraph.setGeometry(QtCore.QRect(20, 170, 331, 331))
        self.polezeroGraph.setObjectName("polezeroGraph")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 530, 1001, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.phaseGraph = PlotWidget(self.widget)
        self.phaseGraph.setObjectName("phaseGraph")
        self.gridLayout.addWidget(self.phaseGraph, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.impulseGraph = PlotWidget(self.widget)
        self.impulseGraph.setObjectName("impulseGraph")
        self.gridLayout.addWidget(self.impulseGraph, 1, 0, 1, 1)
        self.magnitudeGraph = PlotWidget(self.widget)
        self.magnitudeGraph.setObjectName("magnitudeGraph")
        self.gridLayout.addWidget(self.magnitudeGraph, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(410, 410, 608, 51))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(200)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Hz_3 = QtWidgets.QLabel(self.widget1)
        self.label_Hz_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hz_3.setObjectName("label_Hz_3")
        self.gridLayout_2.addWidget(self.label_Hz_3, 0, 1, 1, 1)
        self.label_Hz_2 = QtWidgets.QLabel(self.widget1)
        self.label_Hz_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hz_2.setObjectName("label_Hz_2")
        self.gridLayout_2.addWidget(self.label_Hz_2, 0, 0, 1, 1)
        self.line_pole = QtWidgets.QLineEdit(self.widget1)
        self.line_pole.setObjectName("line_pole")
        self.gridLayout_2.addWidget(self.line_pole, 1, 0, 1, 1)
        self.line_zero = QtWidgets.QLineEdit(self.widget1)
        self.line_zero.setObjectName("line_zero")
        self.gridLayout_2.addWidget(self.line_zero, 1, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(430, 200, 171, 211))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_pole = QtWidgets.QListWidget(self.widget2)
        self.listWidget_pole.setObjectName("listWidget_pole")
        self.verticalLayout_2.addWidget(self.listWidget_pole)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(650, 320, 135, 89))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.line_gain = QtWidgets.QLineEdit(self.widget3)
        self.line_gain.setEnabled(True)
        self.line_gain.setAlignment(QtCore.Qt.AlignCenter)
        self.line_gain.setObjectName("line_gain")
        self.verticalLayout_3.addWidget(self.line_gain)
        self.pushButton_gain = QtWidgets.QPushButton(self.widget3)
        self.pushButton_gain.setObjectName("pushButton_gain")
        self.verticalLayout_3.addWidget(self.pushButton_gain)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(830, 200, 171, 211))
        self.widget4.setObjectName("widget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listWidget_zero = QtWidgets.QListWidget(self.widget4)
        self.listWidget_zero.setObjectName("listWidget_zero")
        self.verticalLayout.addWidget(self.listWidget_zero)
        self.widget5 = QtWidgets.QWidget(self.centralwidget)
        self.widget5.setGeometry(QtCore.QRect(320, 10, 601, 131))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_num = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_num.setFont(font)
        self.label_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_num.setObjectName("label_num")
        self.verticalLayout_4.addWidget(self.label_num)
        self.line = QtWidgets.QFrame(self.widget5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_den = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_den.setFont(font)
        self.label_den.setAlignment(QtCore.Qt.AlignCenter)
        self.label_den.setObjectName("label_den")
        self.verticalLayout_4.addWidget(self.label_den)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(200, 50, 101, 51))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_Hz = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Hz.setFont(font)
        self.label_Hz.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_Hz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hz.setObjectName("label_Hz")
        self.label_ec_gain = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ec_gain.setFont(font)
        self.label_ec_gain.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ec_gain.setObjectName("label_ec_gain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pole-Zero Plot"))
        self.pushButton_addpole.setText(_translate("MainWindow", "Add"))
        self.pushButton_deletepole.setText(_translate("MainWindow", "Delete"))
        self.pushButton_deletezero.setText(_translate("MainWindow", "Delete"))
        self.pushButton_addzero.setText(_translate("MainWindow", "Add"))
        self.label_6.setText(_translate("MainWindow", "Phase Response"))
        self.label_4.setText(_translate("MainWindow", "Impulse Response"))
        self.label_5.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_Hz_3.setText(_translate("MainWindow", "Agregar en ESTE formato binomial ( a+bj )"))
        self.label_Hz_2.setText(_translate("MainWindow", "Agregar en ESTE formato binomial ( a+bj )"))
        self.label_2.setText(_translate("MainWindow", "Pole Location"))
        self.label_7.setText(_translate("MainWindow", "Ganancia"))
        self.label_8.setText(_translate("MainWindow", "Agregar en forma decimal"))
        self.line_gain.setText(_translate("MainWindow", "1"))
        self.pushButton_gain.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Zero Location"))
        self.label_num.setText(_translate("MainWindow", "1"))
        self.label_den.setText(_translate("MainWindow", "1"))
        self.label_Hz.setText(_translate("MainWindow", "H(z) = "))
        self.label_ec_gain.setText(_translate("MainWindow", "1"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

